[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist"

[build.environment]
  NODE_ENV = "production"
  DATABASE_URL = "postgresql://temp:temp@localhost:5432/temp"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 