services:
  - type: web
    name: tids-stempel-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://temp:temp@localhost:5432/temp
      - key: PORT
        value: 5000 